### PR TITLE
Gradle 8.3 + Kotlin 1.9.10

### PR DESCRIPTION
**Pull request by Goooler**
We can kick these thing by enabling @renovate-bot.

### CODE REVIEW

**Comment by ajalt** [comment]
There are a lot of unrelated changes here. Please trim this down to just the version bumps.

**Comment by ajalt** [comment]
I'm not interested in adding renovate or any other bots. Please remove it from the PR and keep the changes limited to just the  kotlin and gradle version bumps.

**Comment by sschuberth** [comment]
There still seem to be changes in here that are not strictly required when bumping versions. @Goooler are you willing to factor these out to separate commits, or @ajalt are you willing to merge this as-is? Because I was about to do the some updates...

**Comment by ajalt** [comment]
Definitely not going to merge as-is. I just did the version bumps in #125

**Pull request closed without merging**
