### PR TITLE
Add Raw Mode Support

### LINKED ISSUE #33: Mordant 2.0: interactive list support
It would be nice to have a Widget to support the interactive selection of items from a list.

Something similar to this:
https://github.com/DmitryBogomolov/cli-list-select

### LINKED ISSUE #89: Feature request: prompt checkbox
Something like this https://www.npmjs.com/package/prompt-checkbox would be extremely useful

### LINKED ISSUE #133: Implement interactive chooser prompt
Do you plan to implement a selectable chooser like in [Gum](https://github.com/charmbracelet/gum) for bash and some JS CLI libs?

[Example](https://camo.githubusercontent.com/49ac1342e46b65283342eb34fd31ed78ee13fa393a65a01c63966a5bb6c6916e/68747470733a2f2f73747566662e636861726d2e73682f67756d2f63686f6f73652e676966)

### LINKED ISSUE #173: Public access to raw user input
Are there any plans to support raw user input that could be used, for example, to process user clicks and create an interactive UI?
Perhaps I looked at it inattentively, but now the library does not provide such an API

### PR DESCRIPTION
**Pull request by ajalt**
Raw mode is supported on all targets except JS and wasm, although there are node/browser APIs to read similar events. I also couldn't get Graal nativeimage working, although that could be added in the future.

select_list

I used to wonder why Jline supports raw mode but all you can do with it is read raw bytes from stdin. But after wading into the mess of parsing VTI escape sequences, I can see why they tapped out. But I'm not willing to push that pain onto users, so I parse all the VTI sequences I can find into `InputEvent` data classes. You can still read raw bytes from stdin instead if you want.

Fixes #173
Fixes #133
Fixes #89
Fixes #33

### CODE REVIEW

**Comment by ajalt** [comment]
Well, that was a lot of work. Mordant targets JVM/jna, JVM/nativeimage, KT/Native, JS, and wasmJS. Multiply that by three operating systems, and any time you touch a syscall you need to implement it a dozen times.

**Comment by Jonathan-Zollinger** [comment]
what was the trouble around compiling with graal ? I remember having a beast of a time getting pico to compile to graal, but I eventually got it working. Is this something I could help with?

**Comment by ajalt** [comment]
I'd love help if you want to take a look. 

The problem is actually kind of silly, but I couldn't figure out how to represent the `tcgetattr`/`tcsetattr` functions with graal's FFI annotations. If you uncomment the code in [SyscallHandler.nativeimage.posix.kt][1] and can get it to compile under nativeimage, that should be all that's required.

[1]: https://github.com/ajalt/mordant/blob/raw-mode/mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.posix.kt

**Comment by Jonathan-Zollinger** [comment]
no guarantees I can actually figure anything out! bug I love the challenge! dont wait up on me, I'm not sure when I'll get to this, but I will get to it!

**Pull request merged**
